#pragma once

// HTML configuration page for WiFi setup
const char config_html[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<meta charset='UTF-8'>"
"<title>WiFi Configuration</title>"
"<style>"
"body{"
"  font-family:Arial,sans-serif;"
"  max-width:400px;"
"  margin:50px auto;"
"  padding:20px;"
"  background:#f5f5f5;"
"}"
"h2{"
"  color:#333;"
"  text-align:center;"
"  margin-bottom:30px;"
"}"
".container{"
"  background:white;"
"  padding:30px;"
"  border-radius:10px;"
"  box-shadow:0 2px 10px rgba(0,0,0,0.1);"
"}"
"label{"
"  display:block;"
"  margin-bottom:5px;"
"  color:#555;"
"  font-weight:bold;"
"}"
"input{"
"  width:100%;"
"  padding:12px;"
"  margin:10px 0 20px 0;"
"  box-sizing:border-box;"
"  border:2px solid #ddd;"
"  border-radius:5px;"
"  font-size:16px;"
"}"
"input:focus{"
"  outline:none;"
"  border-color:#4CAF50;"
"}"
"button{"
"  width:100%;"
"  padding:14px;"
"  background:#4CAF50;"
"  color:white;"
"  border:none;"
"  border-radius:5px;"
"  cursor:pointer;"
"  font-size:16px;"
"  font-weight:bold;"
"}"
"button:hover{"
"  background:#45a049;"
"}"
"button:active{"
"  background:#3d8b40;"
"}"
".info{"
"  background:#e3f2fd;"
"  padding:15px;"
"  border-radius:5px;"
"  margin-bottom:20px;"
"  color:#1976d2;"
"  font-size:14px;"
"}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<h2>WiFi Setup</h2>"
"<div class='info'>"
"Enter your WiFi network credentials below. The device will restart and connect to your network."
"</div>"
"<form action='/save' method='post' onsubmit='return validateForm()'>"
"<label for='ssid'>WiFi Network (SSID):</label>"
"<input type='text' id='ssid' name='ssid' required maxlength='32' placeholder='Enter WiFi network name'>"
"<label for='password'>Password:</label>"
"<input type='password' id='password' name='password' maxlength='64' placeholder='Enter password (leave blank if open)'>"
"<button type='submit'>Save & Connect</button>"
"</form>"
"</div>"
"<script>"
"function validateForm(){"
"  var ssid=document.getElementById('ssid').value;"
"  if(ssid.trim()===''){"
"    alert('Please enter a WiFi network name (SSID)');"
"    return false;"
"  }"
"  if(ssid.length>32){"
"    alert('SSID must be 32 characters or less');"
"    return false;"
"  }"
"  var password=document.getElementById('password').value;"
"  if(password.length>64){"
"    alert('Password must be 64 characters or less');"
"    return false;"
"  }"
"  return confirm('Connect to WiFi network: '+ssid+'?');"
"}"
"</script>"
"</body>"
"</html>";
